### ISSUE TITLE
appendIconSymbol fails in IE

### ISSUE THREAD

**Issue by GU5TAF** [nordnet/react-svg-sprite-icon#4]
<img width="600" alt="screenshot 2016-03-21 12 08 48" src="https://cloud.githubusercontent.com/assets/3854323/13916955/191a9f98-ef5e-11e5-82be-07423c9b5c42.png">

**Comment by bstream** [comment]
Also seems to fail in Phantomjs `PhantomJS 1.9.8 (Mac OS X 0.0.0)`

**Comment by JohnPhoto** [comment]
This is the reason why validated inputs crashes on IE.

**Comment by GU5TAF** [comment]
This is caused by IE's lack of support for innerHTML in Svg's.
I'm looking at using a [polyfill](https://github.com/dnozay/innersvg-polyfill) to solve this.

**Comment by GU5TAF** [comment]
The polyfill added in 9cd43706228280e59203794b83cf35b4fca0bd28 seems to have done the trick, I've updated this package as well as the UI kit that depends on it.
Please let me know how you get on @bstream @JohnPhoto :love_letter:
